= Twig, front matter and page variables

The front matter section of your `index.md` is currently empty, so let's add some information to it and display it on the page.

There are some reserved keywords but, for the most part, you can add whatever you want to the front matter section.

Let's add an author name:

[source,twig]
----
include::index.md[lines=1..3]
----

In YAML, `author` is the key and the value is my name.

Sculpin creates variables from the front matter of each page and makes them available within a `page` variable.

You can then use Twig's print statement to place it within the page content:

[source,twig]
----
include::index.md[lines=5]
----

The variable will be replaced when `{sculpin_generate}` is run, so this is what would be rendered in `index.html`:

[source,html]
----
<p>Hello, Oliver Davies!</p>
----

You can also use more complex YAML structures and Twig features, such as rendering a list of tags on the page.

[source,twig]
----
include::index2.md[]
----

[WARNING]
====
You __can__ put Twig code in `.md` files, but it can cause some odd HTML to be generated.

If a file contains Twig code, it may be better to use a `.twig` or `.html.twig` file.

It will still be converted to a HTML file, but the content won't be parsed as Markdown.
====

== Welcome to SculpinCon!

Let's build a website for a fictional Sculpin conference.

Let's simplify the current page by creating and displaying an appropriate title.

[source,twig]
----
include::index3.md[]
----

The conference will have a CFP (call for papers).

Let's add information about that in the next chapter.
